org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=experimentalist
mod.name=Experimentalist
mod.group=me.pajic
mod.version=2.0.4
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Removes the experimental settings warning screen and allows enabling experimental features globally
mod.sources_url=https://github.com/pajicadvance/experimentalist
mod.homepage_url=https://modrinth.com/mod/experimentalist
mod.issues_url=https://github.com/pajicadvance/experimentalist/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=SKCLXAJ2
publish.curseforge=1161753
publish.github=false
